---
- name: Provision my fedora desktop
  hosts: workstation
  become: true
  vars:
    user: rmanak
  roles:
    - sourcejedi.rpmfusion-nonfree
    - core
    - user
    #- xfce
    #- i3wm
    - btrfs_vault
