---
- name: Provision my fedora laptop
  hosts: workstation
  become: true
  vars:
    user: rmanak
  roles:
    - sourcejedi.rpmfusion-nonfree
    - core
    - desktops
    - laptops
    - i3wm
    - user