# NOTE01: Be sure to modify your /etc/ansible/hosts file to include your hosts!
# NOTE02: Be sure to ssh-add private key!
---
- hosts: local
  become: true
  tasks:
#  - name: Upgrade all installed packages for Debian and Ubuntu
#    apt:
#      upgrade: full
#      force_apt_get: yes
#    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
#
#  - name: Install my list of packages
#    apt: name={{item}} state=present
#    with_items:
#         - zfsutils-linux
#         - keepassx
#         - kdeconnect
#         - git
#         - maven
#         - openjdk-8-jdk
#         - openjdk-11-jdk
#         - procyon-decompiler
#         - qbittorrent
#         - vlc
#         - vim
#         - speedcrunch
#         - python3-pip
#         - hexchat
#         - gimp
#         - awscli
#         - gparted
#         - virtualenv
#         - yakuake
#         - yakuake
#         - tree
#         - openssh-server
#         - gnome-multi-writer
#         - autossh
#         - tmux
#    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  - name: Upgrade all packages on Fedora
    dnf:
      name: "*"
      state: latest
    when: ansible_distribution == "Fedora"
  - name: Install my packages
    package:
      name:
        - vim
        - curl
        - git
        - tmux
        - cmake
        - python-devel
      state: latest
    when: ansible_distribution == "Fedora"
  - name: Enable i3-gaps copr repo
    yum_repository:
      name: i3-gaps_nforro
      description: Copr repo for i3-gaps owned by nforro
      baseurl: https://copr-be.cloud.fedoraproject.org/results/nforro/i3-gaps/fedora-$releasever-$basearch/
      enabled: yes
  - name: Install i3-gaps
    package:
      name:
        - i3-gaps
  - name: Enable heliocastro-hack-fonts copr repo
    yum_repository:
      name: heliocastro-hack-fonts
      description: Copr repo for hack-fonts owned by heliocastro
      baseurl: https://copr-be.cloud.fedoraproject.org/results/heliocastro/hack-fonts/fedora-$releasever-$basearch/
      enabled: yes
  - name: Install hack-fonts
    package:
      name:
        - hack-fonts
  - name: Clone dotfiles from gitlab
    tags: dotbot
    become: rmanak
    git:
      repo: 'git@gitlab.com:RadekManak/dotfiles.git'
      dest: '/home/rmanak/.dotfiles'
      key_file: '/home/rmanak/.ssh/id_rsa'
      accept_hostkey: yes
      recursive: yes
  - name: run dotbot
    tags: dotbot
    become: rmanak
    command: bash /home/rmanak/.dotfiles/install