---
- name: Clone dotfiles from gitlab
  become: "{{ user }}"
  tags: dotbot
  git:
    repo: 'git@github.com:RadekManak/dotfiles.git'
    dest: '~/.dotfiles'
    key_file: '~/.ssh/id_rsa'
    accept_hostkey: yes
    recursive: yes
- name: run dotbot
  become: "{{ user }}"
  tags: dotbot
  command: bash ~/.dotfiles/install
- name: Install vundle and vim plugins
  become: "{{ user }}"
  tags: setupvim
  shell: vim -E -c 'source ~/.vimrc' -c 'PluginInstall' -c 'qa!'
  failed_when: false # Vim exits with code 1. Let's just hope it worked.
  changed_when: false
- name: Install YouCompleteMe dependencies
  tags: setupvim
  become: true
  package:
    name:
      - cmake
      - gcc-c++
      - make
      - python2-devel
      - python3-devel
- name: Install YouCompleteMe vim plugin
  become: "{{ user }}"
  tags: setupvim
  command: "~/.vim/bundle/YouCompleteMe/install.py --clang-completer"
  args:
    creates: "~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so"