---
- name: Clone dotfiles from gitlab
  become: "{{ user }}"
  tags: dotbot
  git:
    repo: 'https://github.com/RadekManak/dotfiles.git'
    dest: '~/.dotfiles'
    key_file: '~/.ssh/id_rsa'
    accept_hostkey: yes
    recursive: yes
  ignore_errors: yes

- name: run dotbot
  become: "{{ user }}"
  tags: dotbot
  command: bash ~/.dotfiles/install
  register: dotbot_out
  changed_when:
    "'Creating' in dotbot_out.stdout"

- name: Install vim-plug and vim plugins
  become: "{{ user }}"
  tags: setupvim
  shell: vim -E -c 'source ~/.vimrc' -c 'PlugInstall' -c 'qa!'
  failed_when: false # Vim exits with code 1. Let's just hope it worked.
  changed_when: false

- name: Install YouCompleteMe dependencies
  tags: setupvim
  become: true
  package:
    name:
      - cmake
      - gcc-c++
      - make
      - python2-devel
      - python3-devel
- name: Install YouCompleteMe vim plugin
  become: "{{ user }}"
  tags: setupvim
  command: "~/.vim/plugged/YouCompleteMe/install.py --clang-completer"
  args:
    creates: "~/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm_core.so"
