---
- name: These packages should be installed on all desktops
  package:
    name:
      - plymouth-theme-charge
      - lightdm
      - slick-greeter
      - pulseaudio
      - vim
      - gvim
      - keepassxc
      - flatpak
      - kde-connect
      - maven
      - java-1.8.0-openjdk-devel
      - qbittorrent
      - speedcrunch
      - hexchat
      #- gimp #conflicts with mypaint on F29 https://bugzilla.redhat.com/show_bug.cgi?id=1633009
      - mypaint
      - gparted
      - gnome-multi-writer
      - libreoffice
      - breeze-cursor-theme
      - numix-icon-theme-circle
      - youtube-dl
      - chromium
      - firefox
      - spectacle
      - dropbox
      - ImageMagick
      - calibre
      - vlc
      - NetworkManager-tui
      - plasma-breeze
      - xdg-utils
    state: present

- name: Ensure system boots into graphical.target
  command: "systemctl set-default graphical.target"
  register: default_target_result
  changed_when: "default_target_result.stderr is search('Created symlink')"

- name: Enable taw/Riot copr repo
  yum_repository:
    name: riot_Taw
    description: Copr repo for Riot owned by taw
    baseurl: https://copr-be.cloud.fedoraproject.org/results/taw/Riot/fedora-$releasever-$basearch/
    enabled: yes

- name: Install Riot
  package:
    name:
      - riot

- name: Add the flathub flatpak repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: uninstall spotify from flathub
  flatpak:
    name: com.spotify.Client
    state: absent
- name: install GIMP from flathub
  flatpak:
    name: org.gimp.GIMP
    state: present

