---
- name: Upgrade all packages on Fedora
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "Fedora"
- name: Install my packages
  package:
    name:
      - vim
      - curl
      - git
      - tmux
      - htop
      - keepassxc
      - flatpak
    state: latest
  when: ansible_distribution == "Fedora"