---
- name: Upgrade all packages on Fedora
  dnf:
    update_cache: yes
    name: "*"
    state: latest
  when: ansible_distribution == "Fedora"

- name: These packages should be installed on every system
  package:
    name:
      - neovim
      - curl
      - git
      - tmux
      - htop
      - wget
    state: present
