---
- name: Upgrade all packages on Fedora
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "Fedora"
- name: Install my packages
  package:
    name:
      - vim
      - curl
      - git
      - tmux
      - htop
      - keepassxc
      - flatpak
      - kdeconnectd
      - maven
      - java-1.8.0-openjdk-devel
      - qbittorrent
      - speedcrunch
      - hexchat
#      - gimp #conflicts with mypaint on F29 https://bugzilla.redhat.com/show_bug.cgi?id=1633009
      - mypaint
      - gparted
      - gnome-multi-writer
      - libreoffice
    state: latest
  when: ansible_distribution == "Fedora"
- name: Remove preinstalled software
  package:
    name:
      - parole
      - pragha
      - abiword
      - gnumeric
      - transmission
    state: absent
  when: ansible_distribution == "Fedora"

- name: get the rpm package facts
  package_facts:
    manager: "auto"

- name: turn on numlock in lightdm
  lineinfile:
    path: "/etc/lightdm/lightdm.conf"
    regexp: '^#greeter-setup-script=$'
    state: present
    line: "greeter-setup-script=/usr/bin/numlockx on"
    backrefs: true
  when: '"lightdm" in ansible_facts.packages'
  notify:
    - Install numlockx