---
- name: Enable livegrenier's i3-desktop copr repository
  yum_repository:
    name: i3-desktop_livegrenier
    description: Copr repo for i3-desktop owned by livegrenier
    baseurl: https://copr-be.cloud.fedoraproject.org/results/livegrenier/i3-desktop/fedora-$releasever-$basearch/
    gpgcheck: yes
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/livegrenier/i3-desktop/pubkey.gpg
    enabled: yes

- name: Disable i3-gaps copr repo
  yum_repository:
    name: i3-gaps_nforro
    description: Copr repo for i3-gaps owned by nforro
    baseurl: https://copr-be.cloud.fedoraproject.org/results/nforro/i3-gaps/fedora-$releasever-$basearch/
    enabled: no

- name: Disable mhartgring/polybar copr repo
  yum_repository:
    name: polybar_mhartgring
    description: Copr repo for polybar owned by mhartgring
    baseurl: https://copr-be.cloud.fedoraproject.org/results/mhartgring/polybar/fedora-$releasever-$basearch/
    enabled: no

- name: Check that the playerctl is installed
  stat:
    path: /usr/bin/playerctl
  register: playerctl_installed

- name: Install playerctl
  dnf:
    name: "https://github.com/acrisci/playerctl/releases/download/v2.0.1/playerctl-2.0.1_x86_64.rpm"
    state: present
  when: playerctl_installed.stat.exists == false

- name: Install software for i3wm
  package:
    name:
      - autorandr #copr i3-desktop
      - i3-gaps # copr i3-desktop
      - polybar # copr i3-desktop
      - xscreensaver
      - light
      - compton
      - nitrogen
      - lxappearance
      - ranger
      - network-manager-applet
      - dunst
      - xfce4-terminal
      - arandr
      - rofi
      - xorg-x11-xinit-session
      - polkit-gnome
